### ISSUE TITLE
Add an item about attendants' consent about recordings

### ISSUE THREAD

**Issue by ProgVal** [erikr/lessobviouschecklist#2]
Ideas:
* Notify attendants there might be recording
* Make it possible for attendants to review recordings before they are published

**Comment by erikr** [comment]
That does seem like a good idea, yes.

It might be very impractical though to allow every person in a recording to review it before publication. What we did at DUTH 2015 is allow people to choose a different lanyard color if they didn't want to be photographed/recorded, and communicated that distinction clearly to everyone. Or do you know of some way to make review before publication scale?

**Comment by ProgVal** [comment]
> It might be very impractical though to allow every person in a recording to review it before publication.

I agree

> What we did at DUTH 2015 is allow people to choose a different lanyard color if they didn't want to be photographed/recorded, and communicated that distinction clearly to everyone.

That looks like a good idea, if lanyard (or similar) are provided.

> Or do you know of some way to make review before publication scale?

No, sorry.

**Comment by erikr** [comment]
Thanks for the suggestion, I added some items :shipit:
